In [1]:
!pip install lightgbm==3.2.0

Requirement already satisfied: lightgbm==3.2.0 in c:\users\dell\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: wheel in c:\users\dell\anaconda3\lib\site-packages (from lightgbm==3.2.0) (0.33.6)
Requirement already satisfied: numpy in c:\users\dell\anaconda3\lib\site-packages (from lightgbm==3.2.0) (1.16.5)
Requirement already satisfied: scipy in c:\users\dell\anaconda3\lib\site-packages (from lightgbm==3.2.0) (1.3.1)
Requirement already satisfied: scikit-learn!=0.22.0 in c:\users\dell\anaconda3\lib\site-packages (from lightgbm==3.2.0) (1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm==3.2.0) (3.1.0)
Requirement already satisfied: joblib>=0.11 in c:\users\dell\anaconda3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm==3.2.0) (0.13.2)

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv("insurance_pre.csv")

In [4]:
dataset = pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
Independent = dataset [['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent = dataset [['charges']]

In [6]:
#from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test = train_test_split(Independent,dependent,test_size=0.30,random_state=0)

In [12]:
from sklearn.model_selection import GridSearchCV
import lightgbm as lgb

grid_params = {'n_estimators':[10,20,30,40,50],'max_depth':[1,2,3,4,5],'random_state':[1,2,3]}

grid = GridSearchCV(lgb.LGBMRegressor(),grid_params,refit=True,verbose=3,n_jobs=-1)

#L = lgb.LGBMRegressor(n_estimators=50, max_depth=3, random_state=5 )
grid.fit(Independent,dependent)

Fitting 5 folds for each of 75 candidates, totalling 375 fits

GridSearchCV(estimator=LGBMRegressor(), n_jobs=-1,
             param_grid={'max_depth': [1, 2, 3, 4, 5],
                         'n_estimators': [10, 20, 30, 40, 50],
                         'random_state': [1, 2, 3]},
             verbose=3)

In [13]:
y_pred = L.predict(Independent)

In [14]:
from sklearn.metrics import r2_score
result = r2_score(dependent,y_pred)
result

0.8758347344505197

In [20]:
result = grid.cv_results_
print(grid.best_params_,grid.best_score_,grid.best_estimator_)

{'max_depth': 3, 'n_estimators': 50, 'random_state': 1} 0.8628231946346219 LGBMRegressor(max_depth=3, n_estimators=50, random_state=1)

In [17]:
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_n_estimators,param_random_state,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.013964,0.002810,0.009592,0.007987,1,10,1,"{'max_depth': 1, 'n_estimators': 10, 'random_s...",0.554022,0.521537,0.541349,0.538470,0.560958,0.543267,0.013620,73
1,0.020838,0.006084,0.010393,0.002243,1,10,2,"{'max_depth': 1, 'n_estimators': 10, 'random_s...",0.554022,0.521537,0.541349,0.538470,0.560958,0.543267,0.013620,73
2,0.020708,0.007484,0.007946,0.003195,1,10,3,"{'max_depth': 1, 'n_estimators': 10, 'random_s...",0.554022,0.521537,0.541349,0.538470,0.560958,0.543267,0.013620,73
3,0.018440,0.009160,0.009399,0.002009,1,20,1,"{'max_depth': 1, 'n_estimators': 20, 'random_s...",0.654517,0.627569,0.645456,0.639141,0.662577,0.645852,0.012118,70
4,0.013500,0.004794,0.007241,0.002635,1,20,2,"{'max_depth': 1, 'n_estimators': 20, 'random_s...",0.654517,0.627569,0.645456,0.639141,0.662577,0.645852,0.012118,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,0.023436,0.006406,0.008428,0.005362,5,40,2,"{'max_depth': 5, 'n_estimators': 40, 'random_s...",0.879579,0.807045,0.891884,0.845087,0.862760,0.857271,0.029655,22
71,0.020120,0.012021,0.007848,0.004961,5,40,3,"{'max_depth': 5, 'n_estimators': 40, 'random_s...",0.879579,0.807045,0.891884,0.845087,0.862760,0.857271,0.029655,22
72,0.018307,0.004532,0.011430,0.006977,5,50,1,"{'max_depth': 5, 'n_estimators': 50, 'random_s...",0.879432,0.805027,0.890906,0.845394,0.860792,0.856310,0.030002,28
73,0.018580,0.007168,0.009958,0.005795,5,50,2,"{'max_depth': 5, 'n_estimators': 50, 'random_s...",0.879432,0.805027,0.890906,0.845394,0.860792,0.856310,0.030002,28
74,0.028471,0.002811,0.004250,0.003611,5,50,3,"{'max_depth': 5, 'n_estimators': 50, 'random_s...",0.879432,0.805027,0.890906,0.845394,0.860792,0.856310,0.030002,28